- alias:
    - theoretisch saldo
  text: Op dag 0 gelijk aan netto kredietsom, daarna theoretische omvang van wat cliënt nog moet terugbetalen als betaalschema volledig volgens plan verloopt. Het theoretisch saldo is dus exclusief kredietvergoeding.
- alias: 
    - uitstaand saldo
  text: Op dag 0 gelijk aan netto kredietsom, daarna omvang van wat hulvrager nog moet terugbetalen op basis van de werkelijke betalingen. Het uitstaand saldo is dus exclusief kredietvergoeding.
- alias:
    - achterstand
  text: Uitstaand saldo -/- theoretisch saldo
- alias:
    - voorstand
  text: Theoretisch saldo -/- uitstaand saldo
- alias:
    - bruto kredietsom
  text: Bedrag uitbetaald aan schuldeisers plus een kredietvergoeding uitgaande van maandaflossing maal de looptijd bij aanvang krediet.
- alias:
    - netto kredietsom
  text: Bedrag uitbetaald aan schuldeisers
- alias:
    - kredietvergoeding
  text: De vergoeding die een kredietbank ontvangt voor de verstrekking en inning van een saneringskrediet.
- alias:
    - te vorderen kredietvergoeding
  text: Kredietvergoeding over de reeds vervallen termijnen van het saneringskrediet.
