openapi: 3.0.3

info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: |

paths:

  /api/mijn-beoordeel-aanvraag-taken:
    get:
      tags:
        - beoordeel aanvraag taken
      summary: Geeft een persoonlijke lijst van beoordeel aanvraag taken.
      description: |
        Geeft een lijst van geclaimde taken. Wanneer de gebruiker geen taken heeft geclaimed dan worden de niet geclaimde taken met de hoogste prioriteit waarvoor de gebruiker geautoriseerd is getoond.
      operationId: GeefMijnBeoordeelAanvraagTakenV1
      parameters:
        - $ref: "../../../data-dictionary/parameters/limit.yml"
        - $ref: "../../../data-dictionary/parameters/offset.yml"
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../../data-dictionary/responses/mijn_taken.yml"
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"

  /api/beoordeel-aanvraag-taken/{taak_id}:
    parameters:        
      - $ref: "../../../data-dictionary/parameters/taak_id.yml"
    get:
      tags:
        - beoordeel aanvraag taken
      summary: Geeft een beoordeel aanvraag taak.
      operationId: GeefBeoordeelAanvraagTaakV1
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../../data-dictionary/responses/beoordeel_aanvraag_taak.yml"
        400:
          $ref: "../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../data-dictionary/responses/types/404.yml"
    patch:      
      tags:
        - beoordeel aanvraag taken
      summary: Vult de aanvraag borgstelling aan met extra informatie.
      operationId: VulBorgstellingAanvraagAanV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "../../../data-dictionary/commands/geef_aanvullende_informatie.yml"
                - $ref: "../../../data-dictionary/commands/beantwoord_aanvullende_vragen.yml"
                - $ref: "../../../data-dictionary/commands/geef_positief_advies.yml"
                - $ref: "../../../data-dictionary/commands/geef_negatief_advies.yml"
              discriminator:
                propertyName: actie
                mapping:
                  geef_informatie: "../../../data-dictionary/commands/geef_aanvullende_informatie.yml"
                  beantwoord_vragen: "../../../data-dictionary/commands/beantwoord_aanvullende_vragen.yml"
                  adviseer_positief: "../../../data-dictionary/commands/geef_positief_advies.yml"
                  adviseer_negatief: "../../../data-dictionary/commands/geef_negatief_advies.yml"
      responses:
        202:
          $ref: "../../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../data-dictionary/responses/types/404.yml"

  /api/beoordeel-aanvraag-taken/{taak_id}/goedkeuren:
    parameters:        
      - $ref: "../../../data-dictionary/parameters/taak_id.yml"
    put:
      tags:
        - beoordeel aanvraag taken
      summary: Keurt de aanvraag borgstelling goed.
      operationId: VoltooiBeoordeelAanvraagTaakMetGoedkeurenV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../../data-dictionary/commands/keur_aanvraag_goed.yml"
      responses:
        202:
          $ref: "../../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../data-dictionary/responses/types/404.yml"

  /api/beoordeel-aanvraag-taken/{taak_id}/afwijzen:
    parameters:        
      - $ref: "../../../data-dictionary/parameters/taak_id.yml"
    put:
      tags:
        - beoordeel aanvraag taken
      summary: Wijst de aanvraag borgstelling af.
      operationId: VoltooiBeoordeelAanvraagTaakMetAfwijzenV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../../data-dictionary/commands/wijs_aanvraag_af.yml"
      responses:
        202:
          $ref: "../../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../data-dictionary/responses/types/404.yml"