actions:
  beeindigen:
    name: borgstelling beëindigen
    schema: 
      $ref: "../../../data-dictionary/commands/beeindig_borgstelling.yml"
    ui:
      hidden:
        - command_id
        - correlation_id
        - causation_id