openapi: 3.0.3

info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: |

paths:

  /api/borgstellingen:
    post:
      tags:
        - borgstellingen
      summary: Registreer aanvraag borgstelling saneringskrediet
      operationId: RegistreerAanvraagBorgstellingV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "../../data-dictionary/commands/registreer_borgstelling_aanvraag.yml"
                - $ref: "../../data-dictionary/commands/registreer_borgstelling_overname.yml"
              discriminator:
                propertyName: soort_aanvraag
                mapping:
                  aanvraag: "../../data-dictionary/commands/registreer_borgstelling_aanvraag.yml"
                  overname: "../../data-dictionary/commands/registreer_borgstelling_overname.yml"
      responses:
        201:
          $ref: "../../data-dictionary/responses/types/201.yml"
        400:
          $ref: "../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../data-dictionary/responses/types/403.yml"