openapi: 3.0.3

info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: |

paths:

  /api/voorbeoordelingen:
    post:
      tags:
        - voorbeoordelingen
      summary: Registreer voorbeoordeling
      operationId: RegistreerVoorbeoordelingV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../data-dictionary/commands/registreer_voorbeoordeling.yml"
      responses:
        201:
          $ref: "../../data-dictionary/responses/types/201.yml"
        400:
          $ref: "../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../data-dictionary/responses/types/403.yml"