openapi: 3.0.3

info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: |
paths:
  
  /api/borgstellingen-dashboard:
    get:      
      tags:
        - borgstellingen
      summary: Geeft het borgstellingen dashboard
      operationId: GeefBorgstellingenDashboardV1
      parameters:        
        - $ref: "../../data-dictionary/parameters/kredietbanken.yml"
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../data-dictionary/responses/geef_borgstellingen_dashboard.yml"
        400:
          $ref: "../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../data-dictionary/responses/types/403.yml"

  /api/borgstellingen:
    get:      
      tags:
        - borgstellingen
      summary: Geeft een lijst met borgstellingen
      operationId: GeefBorgstellingenV1
      parameters:        
        - $ref: "../../data-dictionary/parameters/kredietbanken.yml"
        - $ref: "../../data-dictionary/parameters/kenmerken_kredietbank.yml"
        - $ref: "../../data-dictionary/parameters/limit.yml"
        - $ref: "../../data-dictionary/parameters/offset.yml"
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../data-dictionary/responses/geef_borgstellingen.yml"
        400:
          $ref: "../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../data-dictionary/responses/types/403.yml"

  /api/borgstellingen/{borgstelling_id}:
    parameters:        
      - $ref: "../../data-dictionary/parameters/borgstelling_id.yml"
    get:      
      tags:
        - borgstelling
      summary: Geeft een borgstelling
      operationId: GeefBorgstellingV1
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../data-dictionary/responses/geef_borgstelling.yml"
        400:
          $ref: "../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../data-dictionary/responses/types/404.yml"
    patch:
      tags:
        - borgstelling
      summary: Actieve borgstelling aanvullen met informatie.
      operationId: VulBorgstellingAanV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "../../data-dictionary/commands/verwerk_saneringskrediet_informatie.yml"
              discriminator:
                propertyName: actie
                mapping:
                  verwerk_saneringskrediet_informatie: "../../data-dictionary/commands/verwerk_saneringskrediet_informatie.yml"
      responses:
        202:
          $ref: "../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../data-dictionary/responses/types/404.yml"
