openapi: 3.0.3

info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: |

paths:

  /api/mijn-geef-aanvullende-informatie-taken:
    get:
      tags:
        - geef aanvullende informatie taken
      summary: Geeft een persoonlijke lijst van geef aanvullende informatie taken.
      description: |
        Geeft een lijst van geclaimde taken. Wanneer de gebruiker geen taken heeft geclaimed dan worden de niet geclaimde taken met de hoogste prioriteit waarvoor de gebruiker geautoriseerd is getoond.
      operationId: GeefMijnAanvullendeInformatieTakenV1
      parameters:
        - $ref: "../../../data-dictionary/parameters/limit.yml"
        - $ref: "../../../data-dictionary/parameters/offset.yml"
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../../data-dictionary/responses/mijn_taken.yml"
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"

  /api/geef-aanvullende-informatie-taken/{taak_id}:
    parameters:        
      - $ref: "../../../data-dictionary/parameters/taak_id.yml"
    get:
      tags:
        - geef aanvullende informatie taken
      summary: Geeft een geef aanvullende informatie taak.
      operationId: GeefGeefAanvullendeInformatieTaakV1
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../../data-dictionary/responses/geef_aanvullende_informatie_taak.yml"
        400:
          $ref: "../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../data-dictionary/responses/types/404.yml"

  /api/geef-aanvullende-informatie-taken/{taak_id}/informeren:
    parameters:        
      - $ref: "../../../data-dictionary/parameters/taak_id.yml"
    put:
      tags:
        - geef aanvullende informatie taken
      summary: Voltooit de geef aanvullende informatie taak met informeren.
      operationId: VoltooiGeefAanvullendeInformatieTaakMetInformerenTaakV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../../data-dictionary/commands/geef_aanvullende_informatie.yml"
      responses:
        202:
          $ref: "../../../data-dictionary/responses/types/202.yml"
        400:
          $ref: "../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../data-dictionary/responses/types/404.yml"