openapi: 3.0.3

info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: |

paths:

  /api/borgstellingen/geef-advies-taken/{taak_id}:
    parameters:        
      - $ref: "../../../data-dictionary/parameters/taak_id.yml"
    get:
      tags:
        - geef advies taken
      summary: Geeft een geef advies taak.
      operationId: GeefAdviesTaakV1
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../../data-dictionary/responses/geef_advies_taak.yml"
        400:
          $ref: "../../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../data-dictionary/responses/types/404.yml"
    put:
      tags:
        - geef aanvullende informatie taken
      summary: Voltooit de geef aanvullende informatie taak.
      operationId: VoltooiBeantwoordAanvullendeVragenTaakV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "../../../data-dictionary/commands/geef_positief_advies.yml"
                - $ref: "../../../data-dictionary/commands/geef_negatief_advies.yml"
              discriminator:
                propertyName: actie
      responses:
        202:
          description: Accepted
        401:
          $ref: "../../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../../data-dictionary/responses/types/404.yml"