openapi: 3.0.3

info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: |

paths:

  /api/mijn-taken:
    get:
      tags:
        - mijn taken
      summary: Geeft een persoonlijke lijst van taken.
      description: |
        Geeft een lijst van geclaimde taken. Wanneer de gebruiker geen taken heeft geclaimed dan worden de niet geclaimde takem met de hoogste prioriteit waarvoor de gebruiker geautoiriseerd is getoond.
      operationId: GeefMijnTakenV1
      parameters:
        - $ref: "../../data-dictionary/parameters/limit.yml"
        - $ref: "../../data-dictionary/parameters/offset.yml"
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../data-dictionary/responses/mijn_taken.yml"
        401:
          $ref: "../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../data-dictionary/responses/types/403.yml"