
openapi: 3.0.3

info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: |
paths:

  /api/kredietbanken/{kredietbank_id}/gebeurtenissen:
    parameters:
      - $ref: "../../data-dictionary/parameters/kredietbank_id.yml"
      - $ref: "../../data-dictionary/parameters/offset.yml"
      - $ref: "../../data-dictionary/parameters/limit.yml"
    get:
      tags:
        - gebeurtenissen
      summary: Geeft een lijst met gebeurtenissen.
      operationId: GeefGebeurtenissen
      responses:
        200:          
          description: OK
          content:
            application/json:
              schema:
                $ref: "../../data-dictionary/responses/gebeurtenissen.yml"
        400:
          $ref: "../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../data-dictionary/responses/types/403.yml"