openapi: 3.0.3

info:
  version: 0.0.1
  title: Waarborgfonds saneringskredieten
  description: |
paths:

  /api/borgstellingen/{borgstelling_id}/uitbetalen:
    parameters:        
      - $ref: "../../data-dictionary/parameters/borgstelling_id.yml"
    post:
      tags:
        - borgstelling uitbetalen
      summary: Start het verzoek tot uitbetalen van de borgstelling proces.
      operationId: VerzoekUitbetalingBorgstellingV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../data-dictionary/commands/verzoek_uitbetaling_borgstelling.yml"
      responses:
        201:
          $ref: "../../data-dictionary/responses/types/201.yml"
        400:
          $ref: "../../data-dictionary/responses/types/400.yml"
        401:
          $ref: "../../data-dictionary/responses/types/401.yml"
        403:
          $ref: "../../data-dictionary/responses/types/403.yml"
        404:
          $ref: "../../data-dictionary/responses/types/404.yml"